### ISSUE TITLE
Deserialize Delta struct

### ISSUE THREAD

**Issue by mlesin** [amantoux/quill-delta-rs#2]
I can easily deserialize Vec<Op>, but not whole Delta struct.
Is it possible to add Deserialize derive macro [here](https://github.com/amantoux/quill-delta-rs/blob/14efe668337b6cfe300227d9b8424c44602022ac/src/delta.rs#L19) to simplify this process?

**Comment by amantoux** [comment]
Sure, missed that, will do

**Comment by amantoux** [comment]
Done & published
Please let me know if it works as expected

**Comment by mlesin** [comment]
> Done & published Please let me know if it works as expected

Thanks, looks like it's working as it should!
